2018/08/09 22:01:28 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database '22062018' in C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\YiiRoot\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\YiiRoot\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\YiiRoot\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\YiiRoot\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\prueba\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/prueba/index.php/gii/model/index
HTTP_REFERER=http://localhost/prueba/index.php/gii/model/index
---
2018/08/09 22:01:36 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database '22062018' in C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\YiiRoot\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\YiiRoot\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\YiiRoot\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\YiiRoot\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\prueba\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/prueba/index.php/gii/model/index
HTTP_REFERER=http://localhost/prueba/index.php/gii/default/index
---
2018/08/09 22:01:40 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database '22062018' in C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\YiiRoot\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\YiiRoot\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\YiiRoot\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\YiiRoot\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\prueba\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/prueba/index.php/gii/model/index
HTTP_REFERER=http://localhost/prueba/index.php/gii/default/index
---
2018/08/09 22:02:29 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database '22062018' in C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\YiiRoot\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\YiiRoot\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\YiiRoot\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\YiiRoot\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\YiiRoot\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\YiiRoot\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\YiiRoot\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\YiiRoot\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\prueba\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/prueba/index.php/gii/model/index
HTTP_REFERER=http://localhost/prueba/index.php/gii/default/index
---
2018/08/09 22:07:27 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "carreras". in C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('carreras')
#1 C:\xampp\htdocs\YiiRoot\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prueba\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prueba/index.php/carreras
---
2018/08/09 22:07:31 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "Carreras". in C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('Carreras')
#1 C:\xampp\htdocs\YiiRoot\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prueba\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prueba/index.php/Carreras
---
2018/08/09 22:14:43 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table '20180622.asignaturas_profesor' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `asignaturas_profesor`.
in C:\xampp\htdocs\prueba\index.php (13)
2018/08/09 22:26:37 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "participants". in C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('participants')
#1 C:\xampp\htdocs\YiiRoot\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prueba\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prueba/index.php/participants
---
2018/08/09 23:05:39 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "inscripciones". in C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\YiiRoot\framework\web\CWebApplication.php(141): CWebApplication->runController('inscripciones')
#1 C:\xampp\htdocs\YiiRoot\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prueba\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prueba/index.php/inscripciones
---
